# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-Checker
version:      0.3
version_from: lib/Config/Checker.pm
installdirs:  site
requires:
    Clone::PP:                     0
    FindBin:                       0
    Time::ParseDate:               0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
