--- #YAML:1.0
name:                Config-Checker
version:             0.41
abstract:            Config verification and friendlier YAML
license:             ~
author:              
    - David Muir Sharnoff <muir@idiom.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Clone::PP:                     0
    Eval::LineNumbers:             0
    FindBin:                       0
    Hash::Merge:                   0
    Time::ParseDate:               0
    YAML::Syck:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
